name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Build Android
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          # Instalamos solo lo mínimo vital que usa el motor base
          haxelib install flixel-addons
          haxelib install hxcpp
          haxelib install hscript
          haxelib run lime setup -y
          haxelib run lime setup flixel -y
          haxelib run lime build android
