name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Build Android
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install crypto
          haxelib install hxWebSockets
          haxelib install spine-haxe
          haxelib install linc_luajit
          haxelib install luahscript
          haxelib install hscript-iris-improved
          haxelib install hxvlc
          haxelib install hxCodec
          haxelib install flxanimate
          haxelib install tjson
          haxelib install json2object
          haxelib install funkin.vis
          haxelib install grig.audio
          haxelib install flxsoundfilters
          haxelib install haxeui-core
          haxelib install haxeui-flixel
          haxelib install extension-androidtools
          haxelib install modcharts
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib run lime build android
