name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Build Android
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons
          # Librerías con manejo de errores (si falla, continúa)
          haxelib install crypto || true
          haxelib install hxWebSockets || true
          haxelib install spine-haxe || true
          haxelib install linc_luajit || true
          haxelib install luahscript || true
          haxelib install hscript-iris-improved || true
          haxelib install hxvlc || true
          haxelib install hxCodec || true
          haxelib install flxanimate || true
          haxelib install tjson || true
          haxelib install json2object || true
          haxelib install funkin.vis || true
          haxelib install grig.audio || true
          haxelib install flxsoundfilters || true
          haxelib install haxeui-core || true
          haxelib install haxeui-flixel || true
          haxelib install extension-androidtools || true
          haxelib install modcharts || true
          haxelib run lime setup -y
          haxelib run lime setup flixel -y
          haxelib run lime build android
